### ISSUE TITLE
Tracing Remote EJB Calls 

### ISSUE THREAD

**Issue by kishoremk** [naver/pinpoint-plugin-sample#19]
Will this be able to trace the distributed transactions, involving EJBs ? 
Also if a transaction involves spawning of child threads, will those be traced as well ?

**Comment by lioolli** [comment]
1. Maybe you can write a plugin to trace EJBs but I'm not sure because I don't know how EJB is implemented. 
2. Yes you can trace child thread. Here's an example: https://github.com/naver/pinpoint-plugin-sample/tree/master/plugin/src/main/java/com/navercorp/pinpoint/plugin/sample/_12_Asynchronous_Trace

**Comment by btsinfo** [comment]
Hi @kishoremk , Hi @lioolli , 
please I have full EJB3 applications and with the pinpoint agent no transaction is visible in the WEB pinpoint
